services:
  - type: web
    name: szn-cleaning
    env: node
    plan: free
    rootDir: .
    startCommand: npm start
    buildCommand: npm install && npm run seed
    envVars:
      - key: NODE_ENV
        value: production
